# FOSUserBundle's routing   
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile 
   
# Admin's routing   
sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin
   
admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin
  
  
homepage:
    path: /
    defaults: { _controller: BeluhaBlogBundle:Post:index }
    
authorquote_quote_random:
    path: /random-quote
    defaults:  { _controller: BeluhaBlogBundle:Quote:getRamdomQuote }
    requirements:
        _method:  POST

Beluha_Blog_Post:
    resource: "@BeluhaBlogBundle/Resources/config/routing.yml"
    #resource: "@BeluhaBlogBundle/Controller/PostController.php"
    #type:     annotation
    prefix:   /blog
    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"    